/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ingresos.java
 *
 * Created on Sep 14, 2011, 4:21:56 PM
 */
package proyecto1;

import org.jdesktop.application.Action;

/**
 *
 * @author eddy
 */
public class Ingresos extends javax.swing.JFrame {

    /** Creates new form Ingresos */
    public Ingresos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pAdministrativo = new javax.swing.JButton();
        aerolinea = new javax.swing.JButton();
        aeromoza = new javax.swing.JButton();
        aeropuerto = new javax.swing.JButton();
        avion = new javax.swing.JButton();
        pasajero = new javax.swing.JButton();
        piloto = new javax.swing.JButton();
        vuelo = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(proyecto1.Proyecto1App.class).getContext().getResourceMap(Ingresos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setSize(new java.awt.Dimension(300, 350));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        pAdministrativo.setText(resourceMap.getString("pAdministrativo.text")); // NOI18N
        pAdministrativo.setName("pAdministrativo"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(proyecto1.Proyecto1App.class).getContext().getActionMap(Ingresos.class, this);
        aerolinea.setAction(actionMap.get("nuevaAerolinea")); // NOI18N
        aerolinea.setText(resourceMap.getString("aerolinea.text")); // NOI18N
        aerolinea.setName("aerolinea"); // NOI18N

        aeromoza.setText(resourceMap.getString("aeromoza.text")); // NOI18N
        aeromoza.setName("aeromoza"); // NOI18N

        aeropuerto.setAction(actionMap.get("nuevoAeropuerto")); // NOI18N
        aeropuerto.setText(resourceMap.getString("aeropuerto.text")); // NOI18N
        aeropuerto.setName("aeropuerto"); // NOI18N

        avion.setText(resourceMap.getString("avion.text")); // NOI18N
        avion.setName("avion"); // NOI18N

        pasajero.setText(resourceMap.getString("pasajero.text")); // NOI18N
        pasajero.setName("pasajero"); // NOI18N

        piloto.setText(resourceMap.getString("piloto.text")); // NOI18N
        piloto.setName("piloto"); // NOI18N

        vuelo.setText(resourceMap.getString("vuelo.text")); // NOI18N
        vuelo.setName("vuelo"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(pAdministrativo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(aerolinea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(aeromoza, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(aeropuerto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(avion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(pasajero, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(piloto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(vuelo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(111, 111, 111)
                        .add(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(26, 26, 26)
                .add(pAdministrativo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(aerolinea)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(aeromoza)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(aeropuerto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(avion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pasajero)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(piloto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(vuelo)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ingresos().setVisible(true);
            }
        });
    }
    
    NuevoAeropuerto nuevoAeropuerto = new NuevoAeropuerto();
    NuevaAerolinea nuevaAerolinea = new NuevaAerolinea();
    
    @Action
    public void nuevoAeropuerto() {
        nuevoAeropuerto.setVisible(true);
    }

    @Action
    public void nuevaAerolinea() {
        nuevaAerolinea.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aerolinea;
    private javax.swing.JButton aeromoza;
    private javax.swing.JButton aeropuerto;
    private javax.swing.JButton avion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pAdministrativo;
    private javax.swing.JButton pasajero;
    private javax.swing.JButton piloto;
    private javax.swing.JButton vuelo;
    // End of variables declaration//GEN-END:variables
}
